---
title: "Detailed outline"
output: rmarkdown::html_vignette
toc:
  depth: 2
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Detailed outline}
---

## Week 5


### Before class:

- Video recordings: 2h-2i
- Course notes: chapter 2 (sections 8 and 9)

---

## Week 4


### Before class:

- Video recordings: 2e-2g
- Course notes: chapter 2 (section 5-7)

### In class:

- Workshop on interactions (Exercise 2.8)

## After class:

- Tests of linear hypothesis in **SAS**: [theory](https://documentation.sas.com/?docsetId=statug&docsetTarget=statug_intromod_sect043.htm&docsetVersion=14.3&locale=en), [R code](https://raw.githubusercontent.com/lbelzile/statmod/master/code/60604A-linear_hypothesis_tests.R), [**SAS** code](https://raw.githubusercontent.com/lbelzile/statmod/master/code/60604A-interactions.sas)
- Exercises 2.5-2.7

---

## Week 3


### Before class:

- Video recordings: 2d, 3a
- Course notes: chapter 3, chapter 2 (section 4)

### In class:

- [**R** demo](https://raw.githubusercontent.com/lbelzile/statmod/master/code/60604A-profile.R): sampling distribution of OLS, profile likelihood for individual coefficients
- [Interpretation of **SAS** output and tests for the `insurance` data](https://raw.githubusercontent.com/lbelzile/statmod/master/code/60604A-tests_linear_models.sas)
- [**Understanding Maximum Likelihood** by Kristoffer Magnusson](https://rpsychologist.com/d3/likelihood/)

## After class

- Exercise sheet 3
- [Tests as linear models](https://lindeloev.github.io/tests-as-linear/)

---

## Week 2

### Before class:


- Video recordings: 2a, 2b, 2c
- Course notes: chapter 2 (sections 1-3)

### In class

- Parameter interpretation (`intention` data, full model)
- EDA of the `insurance` data and construction of a linear model
- [Code to create added-variable plots](https://raw.githubusercontent.com/lbelzile/statmod/master/code/60604A-added-variable_plots.sas)
- xkcd comic strip: [Curve-fitting](https://xkcd.com/2048/)

### After class:

- Exercises 2.1-2.4

---

## Week 1

### Before class:

- Video recordings: 0, 1a, 1b, 1c
- Course notes: chapter 1 and Appendix A
- Create an account on **SAS** onDemand 
- Complete the [Introduction to **SAS**](https://lbelzile.github.io/statmod/articles/introSAS.html)

### In class:

- Presentation and practice of pedagogical tools (Zoom / Etherpad / Wooclap / SAS onDemand)
- [Graphics workshop (group)](https://github.com/lbelzile/modstat/raw/master/atelier/graphiques/graphics.zip)

### After class:

- `intro` quiz (self-assessment)
- Exercise 1.4 (a-b) with **SAS**. The whole exercise sheet may be somewhat difficult at this stage, but you should (be able to) complete it in the upcoming weeks.

### Additional readings:

- [Chapter 1 of *Data Visualization: A practical introduction* by Kieran Healy](https://socviz.co/lookatdata.html#lookatdata)
- [Permutation tests](https://www.jwilber.me/permutationtest/)
- [DataViz Cheatsheet](https://policyviz.com/2018/08/07/dataviz-cheatsheet/)
- [Chapter 7 of _**R** for Data Science_ by Garrett Grolemund and Hadley Wickham](https://r4ds.had.co.nz/)

### Other references:

- [Chapter 3 of _**R** for Data Science_ by Garrett Grolemund and Hadley Wickham](https://r4ds.had.co.nz/)
- [*Fundamentals of Data Visualization* by Claus O. Wilke](https://clauswilke.com/dataviz/)
- [Do's and don'ts of making effective graphics](https://stat545.com/effective-graphs.html)
- [Financial Times Visual Vocabulary](	https://github.com/ft-interactive/chart-doctor/tree/master/visual-vocabulary)
- [BBC R Cookbook (optional)](https://bbc.github.io/rcookbook/)
